#CONFIGURAÇÂO DA APLICAÇÂO
spring.application.name=fabrica-nike-api

#BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/fabrica_nike
spring.datasource.username=postgres
spring.datasource.password=2020

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC